name: Release
on:
  pull_request:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get-Version
      id: get-version
      uses: ./
      with:
        RELEASE_BRANCHES_REGEX: '^(stable)$'
        ALLOW_FAILURE: false
        DEBUG: all

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.get-version.outputs.WILL_RELEASE == 'true'
      run: |
        echo "tag_name: v${{ steps.get-version.outputs.VERSION }}"
        echo "release_name: v${{ steps.get-version.outputs.VERSION }}"
        echo "body: v${{ steps.get-version.outputs.VERSION }}"
        echo "prerelease: ${{ steps.get-version.outputs.IS_PRE_RELEASE }}"
